[package]
name = "slipbox-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

[dependencies]
pulldown-cmark = "0.12.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.17"


[[bin]]
name = "main"
